/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RuokalistaRouteImport } from './routes/ruokalista'
import { Route as ReseptiIdRouteImport } from './routes/resepti.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuokalistaRoute = RuokalistaRouteImport.update({
  id: '/ruokalista',
  path: '/ruokalista',
  getParentRoute: () => rootRouteImport,
} as any)
const ReseptiIdRoute = ReseptiIdRouteImport.update({
  id: '/resepti/$id',
  path: '/resepti/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ruokalista': typeof RuokalistaRoute
  '/resepti/$id': typeof ReseptiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ruokalista': typeof RuokalistaRoute
  '/resepti/$id': typeof ReseptiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ruokalista': typeof RuokalistaRoute
  '/resepti/$id': typeof ReseptiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ruokalista' | '/resepti/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ruokalista' | '/resepti/$id'
  id: '__root__' | '/' | '/ruokalista' | '/resepti/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RuokalistaRoute: typeof RuokalistaRoute
  ReseptiIdRoute: typeof ReseptiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruokalista': {
      id: '/ruokalista'
      path: '/ruokalista'
      fullPath: '/ruokalista'
      preLoaderRoute: typeof RuokalistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resepti/$id': {
      id: '/resepti/$id'
      path: '/resepti/$id'
      fullPath: '/resepti/$id'
      preLoaderRoute: typeof ReseptiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RuokalistaRoute: RuokalistaRoute,
  ReseptiIdRoute: ReseptiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
